name: spending_share
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.11.0
  firebase_auth: ^3.3.5
  cloud_firestore: ^3.1.6
  get: ^4.6.1
  http: ^0.13.4
  math_expressions: ^2.3.0
  flutter_screenutil: ^5.2.0
  flutter_svg: ^1.0.3
  provider: ^6.0.2
  google_sign_in: ^5.2.4
  rxdart: ^0.27.3
  syncfusion_flutter_datepicker: ^20.1.48

dev_dependencies:
  mockito: ^5.1.0
  build_runner: ^2.1.7
  fake_cloud_firestore: ^1.2.2
  google_sign_in_mocks: ^0.2.1
  firebase_auth_mocks: ^0.8.3

  flutter_test:
    sdk: flutter

  integration_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/lang/
    - assets/graphics/
    - assets/graphics/icons/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-VariableFont_wght.ttf
